METAFLOW_DEFAULT_METADATA: service
METAFLOW_SERVICE_URL: "https://metaflow-service.example.com"
INGEST_DB_DSN: "postgresql://ingest_user:DB_PASSWORD@INGEST_IP:5432/ingest"
PGSTAC_DSN: "postgresql://pgstac_user:DB_PASSWORD@PGSTAC_IP:5432/pgstac"
